# Generated by Django 3.1.6 on 2021-06-06 20:17

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210304_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.upload_to),
        ),
    ]
