# Generated by Django 3.1.6 on 2021-05-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210501_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='end',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
