# Generated by Django 3.1.6 on 2021-05-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210501_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
