# Generated by Django 3.1.6 on 2021-04-15 19:33

from django.db import migrations, models
import shifts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to=shifts.models.upload_to)),
                ('academic_titles', models.CharField(choices=[('profdr', 'Prof. Dr.'), ('docdr', 'Doç. Dr.'), ('dr', 'Dr.'), ('arastirmadr', 'Araştırma Görevlisi Dr.'), ('arastirma', 'Araştırma Görevlisi')], max_length=20, verbose_name='Ünvan')),
            ],
        ),
    ]
