# Generated by Django 3.1.6 on 2021-04-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='top_title',
            field=models.CharField(blank=True, choices=[('baskan', 'Grup Başkanı'), ('sorumlu', 'Fizik Sorumlusu')], max_length=20, null=True, verbose_name='Görev'),
        ),
    ]
