# Generated by Django 3.1.6 on 2021-04-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shift_top_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['academic_titles']},
        ),
        migrations.AlterField(
            model_name='shift',
            name='academic_titles',
            field=models.CharField(choices=[('0profdr', 'Prof. Dr.'), ('1docdr', 'Doç. Dr.'), ('2dr', 'Dr.'), ('3arastirmadr', 'Araştırma Görevlisi Dr.'), ('4arastirma', 'Araştırma Görevlisi')], max_length=20, verbose_name='Ünvan'),
        ),
    ]
