# Generated by Django 3.1.6 on 2021-06-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_auto_20210421_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='academic_titles',
            field=models.CharField(blank=True, choices=[('0profdr', 'Prof. Dr.'), ('1docdr', 'Doç. Dr.'), ('2dr', 'Dr.'), ('3arastirmadr', 'Araştırma Görevlisi Dr.'), ('4arastirma', 'Araştırma Görevlisi')], max_length=20, null=True, verbose_name='Ünvan'),
        ),
    ]
