# Generated by Django 3.1.6 on 2021-06-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_shiftprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftprofile',
            name='slug',
            field=models.SlugField(default='slug', editable=False, max_length=122, unique=True),
            preserve_default=False,
        ),
    ]
