# Generated by Django 3.1.6 on 2021-06-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_auto_20210617_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='authority_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.authoritytitle'),
        ),
    ]
