# Generated by Django 3.1.6 on 2021-06-17 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_auto_20210617_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='top_title',
        ),
        migrations.AlterField(
            model_name='shift',
            name='academic_titles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='shifts.academictitle'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='authority_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='shifts.authoritytitle'),
        ),
    ]
