# Generated by Django 3.1.6 on 2021-06-17 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_auto_20210618_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='academictitle',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.academictitle'),
        ),
    ]
