# Generated by Django 3.1.6 on 2021-06-17 21:12

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_academictitle_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academictitle',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.academictitle'),
        ),
    ]
