# Generated by Django 3.1.6 on 2021-04-13 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting_reports', '0002_auto_20210412_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingreport',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='meeting_reports.MeetingReportCategory'),
        ),
        migrations.AlterField(
            model_name='meetingreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metting_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='meeting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
