# Generated by Django 3.1.6 on 2021-04-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_reports', '0003_auto_20210413_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
