# Generated by Django 3.1.6 on 2021-04-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_reports', '0004_meeting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='meeting'),
        ),
    ]
