# Generated by Django 3.1.6 on 2021-04-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_reports', '0005_auto_20210415_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingreport',
            options={'ordering': ['-date']},
        ),
    ]
