# Generated by Django 3.1.6 on 2021-05-02 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researchs', to='researchs.categoryresearch'),
        ),
    ]
