# Generated by Django 3.1.6 on 2021-05-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchs', '0002_auto_20210502_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryresearch',
            options={'ordering': ['category_name']},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='research',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=122, unique=True, verbose_name='Slug Alanı'),
        ),
    ]
